### PR TITLE
Added ERC20 events for compatibility with legacy Ðapps

### PR DESCRIPTION
**Pull request by ProphetDaniel**
Trigger ERC20 event for compatibility with legacy ERC20 compatible only Ðapps
Trigger ERC223 event for new ERC223 compatible Ðapps

### CODE REVIEW

**Comment by Dexaran** [comment]
Backwards compatibility with ERC20 token standard is not a goal of ERC223 token standard.
As a result, ERC20 events are implementation details, there is no need to standardized them.

**Comment by Dexaran** [comment]
I don't see any reasons to maintain backwards compatibility with ERC20 tokens. ERC223 is designed to be a standard for both chains Ethereum and EthereumClassic. There are no ERC20 tokens on the ETC. I don't want them to appear because I don't want ETC users to lose money.
If there are no ERC20 tokens and there is no reason to develop them I don't see any reasons to keep backwards compatibility in the standard. 
Also there is a separate branch that aims to keep backwards compatibility with ERC20: https://github.com/Dexaran/ERC23-tokens/tree/ERC20_compatible

**Comment by ProphetDaniel** [comment]
I see @Dexaran you just created the ERC20_compatible branch to keep backwards compatibility with ERC20. Great! I also see the difference of the ERC20_compatible ERC223 and master ERC223 implementations is just an extra event to be triggered. So I suggest people who are creating tokens for either Ethereum to use the ERC20_compatible version just in the case of an Ethereum Ðapp awaiting ERC20 events to work flawlessly with ERC223 tokens. I mean what is the additional cost of an extra event being triggered? Does it outweight the benefit the compatibility brings? I don't think so.

**Comment by ProphetDaniel** [comment]
In the standard it is stated that [ERC223 tokens are backwards compatible](https://github.com/Dexaran/ERC23-tokens/commit/23941970bbf7956f3899c859060c7b7f3f92b41e#diff-04c6e90faac2675aa89e2176d2eec7d8R19). But if ERC20 event is not triggered in fact it will not be.

The classical example is a token wallet which was designed to hold ERC20 tokens when there was no ERC223 standard yet. Users trying to send ERC223 tokens to that wallet would probably face application malfunction due to the fact that the wallet would be awaiting an ERC20 event that would never happen.

**Comment by Dexaran** [comment]
The phrase "standard backward compatibility" means that it is possible to create a token that will work with DApps, which are designed to work with ERC20 and ERC223.
There is a possibility to implement `approve` + `transferFrom` mechanism in ERC20_compatible version of ERC223 token also but I will not recommend to use it.

>  I mean what is the additional cost of an extra event being triggered? Does it outweight the benefit the compatibility brings? 

The ERC223 token standard is designed to be a standard for digital assets on both ETH and ETC chains. There are no ERC20 tokens on ETC chain. There is no benefit from backward compatibility with non-existent things.

**Pull request closed without merging**
